name: country_calling_code_picker
description: Flexible Country picker for getting Country code and Calling code.
version: 1.0.8
homepage: https://github.com/IRFAN-GujjAR/country-calling-code-picker.git
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sim_country_code: 
    git:
      url: https://github.com/IRFAN-GujjAR/flutter_sim_country_code.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flags/
    - raw/
